import json
import subprocess

diagnosis = json.load(open("diagnosis.json"))

title = "Auto-fix CI failure"

body = f"""
## Root Cause

{diagnosis['root_cause']}

## Proposed Fix

{diagnosis['proposed_fix']}

Generated by Mistral CI Agent.
"""

subprocess.run(
    [
        "gh",
        "pr",
        "create",
        "--title",
        title,
        "--body",
        body
    ],
    check=True
)
